language: cpp
compiler: gcc
sudo: require
dist: trusty

install:
  - sudo apt-get -y install qt4-dev-tools libjpeg-dev zlib1g-dev libpng-dev libtiff-dev libboost-all-dev libxrender-dev

script:
  - cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  - make -j$(nproc)
  - make DESTDIR=appdir -j$(nproc) install ; find appdir/
  - mkdir -p ./appdir/usr/share/metainfo/ ; cp ./packaging/linux/scantailor.appdata.xml ./appdir/usr/share/metainfo/
  - mkdir -p ./appdir/usr/share/applications/ ; cp ./packaging/linux/scantailor.desktop ./appdir/usr/share/applications/
  - mkdir -p ./appdir/usr/share/icons/hicolor/scalable/apps ; cp ./resources/appicon.svg ./appdir/usr/share/icons/hicolor/scalable/apps/scantailor.svg
  - cp ./resources/appicon.svg ./appdir/scantailor.svg
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage -executable=appdir/usr/bin/scantailor-cli

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Scan*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
