# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.4.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.4.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/pod/scantailor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/pod/scantailor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/Cellar/cmake/3.4.3/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.4.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.4.3/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.4.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.4.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.4.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.4.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/Cellar/cmake/3.4.3/bin/cpack --config ./CPackSourceConfig.cmake /Users/pod/scantailor/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pod/scantailor/CMakeFiles /Users/pod/scantailor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pod/scantailor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named compile_translations

# Build rule for target.
compile_translations: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compile_translations
.PHONY : compile_translations

# fast build rule for target.
compile_translations/fast:
	$(MAKE) -f CMakeFiles/compile_translations.dir/build.make CMakeFiles/compile_translations.dir/build
.PHONY : compile_translations/fast

#=============================================================================
# Target rules for targets named scantailor

# Build rule for target.
scantailor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scantailor
.PHONY : scantailor

# fast build rule for target.
scantailor/fast:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/build
.PHONY : scantailor/fast

#=============================================================================
# Target rules for targets named scantailor-cli

# Build rule for target.
scantailor-cli: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scantailor-cli
.PHONY : scantailor-cli

# fast build rule for target.
scantailor-cli/fast:
	$(MAKE) -f CMakeFiles/scantailor-cli.dir/build.make CMakeFiles/scantailor-cli.dir/build
.PHONY : scantailor-cli/fast

#=============================================================================
# Target rules for targets named stcore

# Build rule for target.
stcore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stcore
.PHONY : stcore

# fast build rule for target.
stcore/fast:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/build
.PHONY : stcore/fast

#=============================================================================
# Target rules for targets named toplevel_ui_sources

# Build rule for target.
toplevel_ui_sources: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 toplevel_ui_sources
.PHONY : toplevel_ui_sources

# fast build rule for target.
toplevel_ui_sources/fast:
	$(MAKE) -f CMakeFiles/toplevel_ui_sources.dir/build.make CMakeFiles/toplevel_ui_sources.dir/build
.PHONY : toplevel_ui_sources/fast

#=============================================================================
# Target rules for targets named update_translations

# Build rule for target.
update_translations: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update_translations
.PHONY : update_translations

# fast build rule for target.
update_translations/fast:
	$(MAKE) -f CMakeFiles/update_translations.dir/build.make CMakeFiles/update_translations.dir/build
.PHONY : update_translations/fast

#=============================================================================
# Target rules for targets named dewarping

# Build rule for target.
dewarping: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dewarping
.PHONY : dewarping

# fast build rule for target.
dewarping/fast:
	$(MAKE) -f dewarping/CMakeFiles/dewarping.dir/build.make dewarping/CMakeFiles/dewarping.dir/build
.PHONY : dewarping/fast

#=============================================================================
# Target rules for targets named foundation

# Build rule for target.
foundation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 foundation
.PHONY : foundation

# fast build rule for target.
foundation/fast:
	$(MAKE) -f foundation/CMakeFiles/foundation.dir/build.make foundation/CMakeFiles/foundation.dir/build
.PHONY : foundation/fast

#=============================================================================
# Target rules for targets named math

# Build rule for target.
math: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 math
.PHONY : math

# fast build rule for target.
math/fast:
	$(MAKE) -f math/CMakeFiles/math.dir/build.make math/CMakeFiles/math.dir/build
.PHONY : math/fast

#=============================================================================
# Target rules for targets named spfit_tests

# Build rule for target.
spfit_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spfit_tests
.PHONY : spfit_tests

# fast build rule for target.
spfit_tests/fast:
	$(MAKE) -f math/spfit/tests/CMakeFiles/spfit_tests.dir/build.make math/spfit/tests/CMakeFiles/spfit_tests.dir/build
.PHONY : spfit_tests/fast

#=============================================================================
# Target rules for targets named adiff_tests

# Build rule for target.
adiff_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 adiff_tests
.PHONY : adiff_tests

# fast build rule for target.
adiff_tests/fast:
	$(MAKE) -f math/adiff/tests/CMakeFiles/adiff_tests.dir/build.make math/adiff/tests/CMakeFiles/adiff_tests.dir/build
.PHONY : adiff_tests/fast

#=============================================================================
# Target rules for targets named imageproc

# Build rule for target.
imageproc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imageproc
.PHONY : imageproc

# fast build rule for target.
imageproc/fast:
	$(MAKE) -f imageproc/CMakeFiles/imageproc.dir/build.make imageproc/CMakeFiles/imageproc.dir/build
.PHONY : imageproc/fast

#=============================================================================
# Target rules for targets named imageproc_tests

# Build rule for target.
imageproc_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imageproc_tests
.PHONY : imageproc_tests

# fast build rule for target.
imageproc_tests/fast:
	$(MAKE) -f imageproc/tests/CMakeFiles/imageproc_tests.dir/build.make imageproc/tests/CMakeFiles/imageproc_tests.dir/build
.PHONY : imageproc_tests/fast

#=============================================================================
# Target rules for targets named interaction

# Build rule for target.
interaction: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 interaction
.PHONY : interaction

# fast build rule for target.
interaction/fast:
	$(MAKE) -f interaction/CMakeFiles/interaction.dir/build.make interaction/CMakeFiles/interaction.dir/build
.PHONY : interaction/fast

#=============================================================================
# Target rules for targets named zones

# Build rule for target.
zones: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zones
.PHONY : zones

# fast build rule for target.
zones/fast:
	$(MAKE) -f zones/CMakeFiles/zones.dir/build.make zones/CMakeFiles/zones.dir/build
.PHONY : zones/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f tests/CMakeFiles/tests.dir/build.make tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named fix_orientation

# Build rule for target.
fix_orientation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fix_orientation
.PHONY : fix_orientation

# fast build rule for target.
fix_orientation/fast:
	$(MAKE) -f filters/fix_orientation/CMakeFiles/fix_orientation.dir/build.make filters/fix_orientation/CMakeFiles/fix_orientation.dir/build
.PHONY : fix_orientation/fast

#=============================================================================
# Target rules for targets named page_split

# Build rule for target.
page_split: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 page_split
.PHONY : page_split

# fast build rule for target.
page_split/fast:
	$(MAKE) -f filters/page_split/CMakeFiles/page_split.dir/build.make filters/page_split/CMakeFiles/page_split.dir/build
.PHONY : page_split/fast

#=============================================================================
# Target rules for targets named deskew

# Build rule for target.
deskew: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deskew
.PHONY : deskew

# fast build rule for target.
deskew/fast:
	$(MAKE) -f filters/deskew/CMakeFiles/deskew.dir/build.make filters/deskew/CMakeFiles/deskew.dir/build
.PHONY : deskew/fast

#=============================================================================
# Target rules for targets named select_content

# Build rule for target.
select_content: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 select_content
.PHONY : select_content

# fast build rule for target.
select_content/fast:
	$(MAKE) -f filters/select_content/CMakeFiles/select_content.dir/build.make filters/select_content/CMakeFiles/select_content.dir/build
.PHONY : select_content/fast

#=============================================================================
# Target rules for targets named page_layout

# Build rule for target.
page_layout: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 page_layout
.PHONY : page_layout

# fast build rule for target.
page_layout/fast:
	$(MAKE) -f filters/page_layout/CMakeFiles/page_layout.dir/build.make filters/page_layout/CMakeFiles/page_layout.dir/build
.PHONY : page_layout/fast

#=============================================================================
# Target rules for targets named output

# Build rule for target.
output: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 output
.PHONY : output

# fast build rule for target.
output/fast:
	$(MAKE) -f filters/output/CMakeFiles/output.dir/build.make filters/output/CMakeFiles/output.dir/build
.PHONY : output/fast

Application.o: Application.cpp.o

.PHONY : Application.o

# target to build an object file
Application.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/Application.cpp.o
.PHONY : Application.cpp.o

Application.i: Application.cpp.i

.PHONY : Application.i

# target to preprocess a source file
Application.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/Application.cpp.i
.PHONY : Application.cpp.i

Application.s: Application.cpp.s

.PHONY : Application.s

# target to generate assembly for a file
Application.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/Application.cpp.s
.PHONY : Application.cpp.s

AtomicFileOverwriter.o: AtomicFileOverwriter.cpp.o

.PHONY : AtomicFileOverwriter.o

# target to build an object file
AtomicFileOverwriter.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/AtomicFileOverwriter.cpp.o
.PHONY : AtomicFileOverwriter.cpp.o

AtomicFileOverwriter.i: AtomicFileOverwriter.cpp.i

.PHONY : AtomicFileOverwriter.i

# target to preprocess a source file
AtomicFileOverwriter.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/AtomicFileOverwriter.cpp.i
.PHONY : AtomicFileOverwriter.cpp.i

AtomicFileOverwriter.s: AtomicFileOverwriter.cpp.s

.PHONY : AtomicFileOverwriter.s

# target to generate assembly for a file
AtomicFileOverwriter.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/AtomicFileOverwriter.cpp.s
.PHONY : AtomicFileOverwriter.cpp.s

BackgroundExecutor.o: BackgroundExecutor.cpp.o

.PHONY : BackgroundExecutor.o

# target to build an object file
BackgroundExecutor.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/BackgroundExecutor.cpp.o
.PHONY : BackgroundExecutor.cpp.o

BackgroundExecutor.i: BackgroundExecutor.cpp.i

.PHONY : BackgroundExecutor.i

# target to preprocess a source file
BackgroundExecutor.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/BackgroundExecutor.cpp.i
.PHONY : BackgroundExecutor.cpp.i

BackgroundExecutor.s: BackgroundExecutor.cpp.s

.PHONY : BackgroundExecutor.s

# target to generate assembly for a file
BackgroundExecutor.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/BackgroundExecutor.cpp.s
.PHONY : BackgroundExecutor.cpp.s

BackgroundTask.o: BackgroundTask.cpp.o

.PHONY : BackgroundTask.o

# target to build an object file
BackgroundTask.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/BackgroundTask.cpp.o
.PHONY : BackgroundTask.cpp.o

BackgroundTask.i: BackgroundTask.cpp.i

.PHONY : BackgroundTask.i

# target to preprocess a source file
BackgroundTask.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/BackgroundTask.cpp.i
.PHONY : BackgroundTask.cpp.i

BackgroundTask.s: BackgroundTask.cpp.s

.PHONY : BackgroundTask.s

# target to generate assembly for a file
BackgroundTask.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/BackgroundTask.cpp.s
.PHONY : BackgroundTask.cpp.s

BasicImageView.o: BasicImageView.cpp.o

.PHONY : BasicImageView.o

# target to build an object file
BasicImageView.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/BasicImageView.cpp.o
.PHONY : BasicImageView.cpp.o

BasicImageView.i: BasicImageView.cpp.i

.PHONY : BasicImageView.i

# target to preprocess a source file
BasicImageView.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/BasicImageView.cpp.i
.PHONY : BasicImageView.cpp.i

BasicImageView.s: BasicImageView.cpp.s

.PHONY : BasicImageView.s

# target to generate assembly for a file
BasicImageView.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/BasicImageView.cpp.s
.PHONY : BasicImageView.cpp.s

BubbleAnimation.o: BubbleAnimation.cpp.o

.PHONY : BubbleAnimation.o

# target to build an object file
BubbleAnimation.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/BubbleAnimation.cpp.o
.PHONY : BubbleAnimation.cpp.o

BubbleAnimation.i: BubbleAnimation.cpp.i

.PHONY : BubbleAnimation.i

# target to preprocess a source file
BubbleAnimation.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/BubbleAnimation.cpp.i
.PHONY : BubbleAnimation.cpp.i

BubbleAnimation.s: BubbleAnimation.cpp.s

.PHONY : BubbleAnimation.s

# target to generate assembly for a file
BubbleAnimation.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/BubbleAnimation.cpp.s
.PHONY : BubbleAnimation.cpp.s

CommandLine.o: CommandLine.cpp.o

.PHONY : CommandLine.o

# target to build an object file
CommandLine.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/CommandLine.cpp.o
.PHONY : CommandLine.cpp.o

CommandLine.i: CommandLine.cpp.i

.PHONY : CommandLine.i

# target to preprocess a source file
CommandLine.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/CommandLine.cpp.i
.PHONY : CommandLine.cpp.i

CommandLine.s: CommandLine.cpp.s

.PHONY : CommandLine.s

# target to generate assembly for a file
CommandLine.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/CommandLine.cpp.s
.PHONY : CommandLine.cpp.s

ConsoleBatch.o: ConsoleBatch.cpp.o

.PHONY : ConsoleBatch.o

# target to build an object file
ConsoleBatch.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor-cli.dir/build.make CMakeFiles/scantailor-cli.dir/ConsoleBatch.cpp.o
.PHONY : ConsoleBatch.cpp.o

ConsoleBatch.i: ConsoleBatch.cpp.i

.PHONY : ConsoleBatch.i

# target to preprocess a source file
ConsoleBatch.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor-cli.dir/build.make CMakeFiles/scantailor-cli.dir/ConsoleBatch.cpp.i
.PHONY : ConsoleBatch.cpp.i

ConsoleBatch.s: ConsoleBatch.cpp.s

.PHONY : ConsoleBatch.s

# target to generate assembly for a file
ConsoleBatch.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor-cli.dir/build.make CMakeFiles/scantailor-cli.dir/ConsoleBatch.cpp.s
.PHONY : ConsoleBatch.cpp.s

ContentBoxPropagator.o: ContentBoxPropagator.cpp.o

.PHONY : ContentBoxPropagator.o

# target to build an object file
ContentBoxPropagator.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ContentBoxPropagator.cpp.o
.PHONY : ContentBoxPropagator.cpp.o

ContentBoxPropagator.i: ContentBoxPropagator.cpp.i

.PHONY : ContentBoxPropagator.i

# target to preprocess a source file
ContentBoxPropagator.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ContentBoxPropagator.cpp.i
.PHONY : ContentBoxPropagator.cpp.i

ContentBoxPropagator.s: ContentBoxPropagator.cpp.s

.PHONY : ContentBoxPropagator.s

# target to generate assembly for a file
ContentBoxPropagator.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ContentBoxPropagator.cpp.s
.PHONY : ContentBoxPropagator.cpp.s

ContentSpanFinder.o: ContentSpanFinder.cpp.o

.PHONY : ContentSpanFinder.o

# target to build an object file
ContentSpanFinder.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ContentSpanFinder.cpp.o
.PHONY : ContentSpanFinder.cpp.o

ContentSpanFinder.i: ContentSpanFinder.cpp.i

.PHONY : ContentSpanFinder.i

# target to preprocess a source file
ContentSpanFinder.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ContentSpanFinder.cpp.i
.PHONY : ContentSpanFinder.cpp.i

ContentSpanFinder.s: ContentSpanFinder.cpp.s

.PHONY : ContentSpanFinder.s

# target to generate assembly for a file
ContentSpanFinder.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ContentSpanFinder.cpp.s
.PHONY : ContentSpanFinder.cpp.s

DebugImageView.o: DebugImageView.cpp.o

.PHONY : DebugImageView.o

# target to build an object file
DebugImageView.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/DebugImageView.cpp.o
.PHONY : DebugImageView.cpp.o

DebugImageView.i: DebugImageView.cpp.i

.PHONY : DebugImageView.i

# target to preprocess a source file
DebugImageView.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/DebugImageView.cpp.i
.PHONY : DebugImageView.cpp.i

DebugImageView.s: DebugImageView.cpp.s

.PHONY : DebugImageView.s

# target to generate assembly for a file
DebugImageView.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/DebugImageView.cpp.s
.PHONY : DebugImageView.cpp.s

DebugImages.o: DebugImages.cpp.o

.PHONY : DebugImages.o

# target to build an object file
DebugImages.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/DebugImages.cpp.o
.PHONY : DebugImages.cpp.o

DebugImages.i: DebugImages.cpp.i

.PHONY : DebugImages.i

# target to preprocess a source file
DebugImages.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/DebugImages.cpp.i
.PHONY : DebugImages.cpp.i

DebugImages.s: DebugImages.cpp.s

.PHONY : DebugImages.s

# target to generate assembly for a file
DebugImages.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/DebugImages.cpp.s
.PHONY : DebugImages.cpp.s

Despeckle.o: Despeckle.cpp.o

.PHONY : Despeckle.o

# target to build an object file
Despeckle.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/Despeckle.cpp.o
.PHONY : Despeckle.cpp.o

Despeckle.i: Despeckle.cpp.i

.PHONY : Despeckle.i

# target to preprocess a source file
Despeckle.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/Despeckle.cpp.i
.PHONY : Despeckle.cpp.i

Despeckle.s: Despeckle.cpp.s

.PHONY : Despeckle.s

# target to generate assembly for a file
Despeckle.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/Despeckle.cpp.s
.PHONY : Despeckle.cpp.s

Dpi.o: Dpi.cpp.o

.PHONY : Dpi.o

# target to build an object file
Dpi.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/Dpi.cpp.o
.PHONY : Dpi.cpp.o

Dpi.i: Dpi.cpp.i

.PHONY : Dpi.i

# target to preprocess a source file
Dpi.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/Dpi.cpp.i
.PHONY : Dpi.cpp.i

Dpi.s: Dpi.cpp.s

.PHONY : Dpi.s

# target to generate assembly for a file
Dpi.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/Dpi.cpp.s
.PHONY : Dpi.cpp.s

Dpm.o: Dpm.cpp.o

.PHONY : Dpm.o

# target to build an object file
Dpm.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/Dpm.cpp.o
.PHONY : Dpm.cpp.o

Dpm.i: Dpm.cpp.i

.PHONY : Dpm.i

# target to preprocess a source file
Dpm.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/Dpm.cpp.i
.PHONY : Dpm.cpp.i

Dpm.s: Dpm.cpp.s

.PHONY : Dpm.s

# target to generate assembly for a file
Dpm.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/Dpm.cpp.s
.PHONY : Dpm.cpp.s

ErrorWidget.o: ErrorWidget.cpp.o

.PHONY : ErrorWidget.o

# target to build an object file
ErrorWidget.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ErrorWidget.cpp.o
.PHONY : ErrorWidget.cpp.o

ErrorWidget.i: ErrorWidget.cpp.i

.PHONY : ErrorWidget.i

# target to preprocess a source file
ErrorWidget.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ErrorWidget.cpp.i
.PHONY : ErrorWidget.cpp.i

ErrorWidget.s: ErrorWidget.cpp.s

.PHONY : ErrorWidget.s

# target to generate assembly for a file
ErrorWidget.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ErrorWidget.cpp.s
.PHONY : ErrorWidget.cpp.s

EstimateBackground.o: EstimateBackground.cpp.o

.PHONY : EstimateBackground.o

# target to build an object file
EstimateBackground.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/EstimateBackground.cpp.o
.PHONY : EstimateBackground.cpp.o

EstimateBackground.i: EstimateBackground.cpp.i

.PHONY : EstimateBackground.i

# target to preprocess a source file
EstimateBackground.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/EstimateBackground.cpp.i
.PHONY : EstimateBackground.cpp.i

EstimateBackground.s: EstimateBackground.cpp.s

.PHONY : EstimateBackground.s

# target to generate assembly for a file
EstimateBackground.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/EstimateBackground.cpp.s
.PHONY : EstimateBackground.cpp.s

ExportDialog.o: ExportDialog.cpp.o

.PHONY : ExportDialog.o

# target to build an object file
ExportDialog.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/ExportDialog.cpp.o
.PHONY : ExportDialog.cpp.o

ExportDialog.i: ExportDialog.cpp.i

.PHONY : ExportDialog.i

# target to preprocess a source file
ExportDialog.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/ExportDialog.cpp.i
.PHONY : ExportDialog.cpp.i

ExportDialog.s: ExportDialog.cpp.s

.PHONY : ExportDialog.s

# target to generate assembly for a file
ExportDialog.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/ExportDialog.cpp.s
.PHONY : ExportDialog.cpp.s

FileNameDisambiguator.o: FileNameDisambiguator.cpp.o

.PHONY : FileNameDisambiguator.o

# target to build an object file
FileNameDisambiguator.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/FileNameDisambiguator.cpp.o
.PHONY : FileNameDisambiguator.cpp.o

FileNameDisambiguator.i: FileNameDisambiguator.cpp.i

.PHONY : FileNameDisambiguator.i

# target to preprocess a source file
FileNameDisambiguator.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/FileNameDisambiguator.cpp.i
.PHONY : FileNameDisambiguator.cpp.i

FileNameDisambiguator.s: FileNameDisambiguator.cpp.s

.PHONY : FileNameDisambiguator.s

# target to generate assembly for a file
FileNameDisambiguator.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/FileNameDisambiguator.cpp.s
.PHONY : FileNameDisambiguator.cpp.s

FilterData.o: FilterData.cpp.o

.PHONY : FilterData.o

# target to build an object file
FilterData.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/FilterData.cpp.o
.PHONY : FilterData.cpp.o

FilterData.i: FilterData.cpp.i

.PHONY : FilterData.i

# target to preprocess a source file
FilterData.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/FilterData.cpp.i
.PHONY : FilterData.cpp.i

FilterData.s: FilterData.cpp.s

.PHONY : FilterData.s

# target to generate assembly for a file
FilterData.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/FilterData.cpp.s
.PHONY : FilterData.cpp.s

FilterOptionsWidget.o: FilterOptionsWidget.cpp.o

.PHONY : FilterOptionsWidget.o

# target to build an object file
FilterOptionsWidget.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/FilterOptionsWidget.cpp.o
.PHONY : FilterOptionsWidget.cpp.o

FilterOptionsWidget.i: FilterOptionsWidget.cpp.i

.PHONY : FilterOptionsWidget.i

# target to preprocess a source file
FilterOptionsWidget.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/FilterOptionsWidget.cpp.i
.PHONY : FilterOptionsWidget.cpp.i

FilterOptionsWidget.s: FilterOptionsWidget.cpp.s

.PHONY : FilterOptionsWidget.s

# target to generate assembly for a file
FilterOptionsWidget.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/FilterOptionsWidget.cpp.s
.PHONY : FilterOptionsWidget.cpp.s

FixDpiDialog.o: FixDpiDialog.cpp.o

.PHONY : FixDpiDialog.o

# target to build an object file
FixDpiDialog.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/FixDpiDialog.cpp.o
.PHONY : FixDpiDialog.cpp.o

FixDpiDialog.i: FixDpiDialog.cpp.i

.PHONY : FixDpiDialog.i

# target to preprocess a source file
FixDpiDialog.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/FixDpiDialog.cpp.i
.PHONY : FixDpiDialog.cpp.i

FixDpiDialog.s: FixDpiDialog.cpp.s

.PHONY : FixDpiDialog.s

# target to generate assembly for a file
FixDpiDialog.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/FixDpiDialog.cpp.s
.PHONY : FixDpiDialog.cpp.s

ImageFileInfo.o: ImageFileInfo.cpp.o

.PHONY : ImageFileInfo.o

# target to build an object file
ImageFileInfo.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageFileInfo.cpp.o
.PHONY : ImageFileInfo.cpp.o

ImageFileInfo.i: ImageFileInfo.cpp.i

.PHONY : ImageFileInfo.i

# target to preprocess a source file
ImageFileInfo.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageFileInfo.cpp.i
.PHONY : ImageFileInfo.cpp.i

ImageFileInfo.s: ImageFileInfo.cpp.s

.PHONY : ImageFileInfo.s

# target to generate assembly for a file
ImageFileInfo.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageFileInfo.cpp.s
.PHONY : ImageFileInfo.cpp.s

ImageId.o: ImageId.cpp.o

.PHONY : ImageId.o

# target to build an object file
ImageId.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageId.cpp.o
.PHONY : ImageId.cpp.o

ImageId.i: ImageId.cpp.i

.PHONY : ImageId.i

# target to preprocess a source file
ImageId.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageId.cpp.i
.PHONY : ImageId.cpp.i

ImageId.s: ImageId.cpp.s

.PHONY : ImageId.s

# target to generate assembly for a file
ImageId.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageId.cpp.s
.PHONY : ImageId.cpp.s

ImageInfo.o: ImageInfo.cpp.o

.PHONY : ImageInfo.o

# target to build an object file
ImageInfo.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageInfo.cpp.o
.PHONY : ImageInfo.cpp.o

ImageInfo.i: ImageInfo.cpp.i

.PHONY : ImageInfo.i

# target to preprocess a source file
ImageInfo.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageInfo.cpp.i
.PHONY : ImageInfo.cpp.i

ImageInfo.s: ImageInfo.cpp.s

.PHONY : ImageInfo.s

# target to generate assembly for a file
ImageInfo.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageInfo.cpp.s
.PHONY : ImageInfo.cpp.s

ImageLoader.o: ImageLoader.cpp.o

.PHONY : ImageLoader.o

# target to build an object file
ImageLoader.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageLoader.cpp.o
.PHONY : ImageLoader.cpp.o

ImageLoader.i: ImageLoader.cpp.i

.PHONY : ImageLoader.i

# target to preprocess a source file
ImageLoader.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageLoader.cpp.i
.PHONY : ImageLoader.cpp.i

ImageLoader.s: ImageLoader.cpp.s

.PHONY : ImageLoader.s

# target to generate assembly for a file
ImageLoader.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageLoader.cpp.s
.PHONY : ImageLoader.cpp.s

ImageMetadata.o: ImageMetadata.cpp.o

.PHONY : ImageMetadata.o

# target to build an object file
ImageMetadata.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageMetadata.cpp.o
.PHONY : ImageMetadata.cpp.o

ImageMetadata.i: ImageMetadata.cpp.i

.PHONY : ImageMetadata.i

# target to preprocess a source file
ImageMetadata.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageMetadata.cpp.i
.PHONY : ImageMetadata.cpp.i

ImageMetadata.s: ImageMetadata.cpp.s

.PHONY : ImageMetadata.s

# target to generate assembly for a file
ImageMetadata.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageMetadata.cpp.s
.PHONY : ImageMetadata.cpp.s

ImageMetadataLoader.o: ImageMetadataLoader.cpp.o

.PHONY : ImageMetadataLoader.o

# target to build an object file
ImageMetadataLoader.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageMetadataLoader.cpp.o
.PHONY : ImageMetadataLoader.cpp.o

ImageMetadataLoader.i: ImageMetadataLoader.cpp.i

.PHONY : ImageMetadataLoader.i

# target to preprocess a source file
ImageMetadataLoader.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageMetadataLoader.cpp.i
.PHONY : ImageMetadataLoader.cpp.i

ImageMetadataLoader.s: ImageMetadataLoader.cpp.s

.PHONY : ImageMetadataLoader.s

# target to generate assembly for a file
ImageMetadataLoader.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageMetadataLoader.cpp.s
.PHONY : ImageMetadataLoader.cpp.s

ImageTransformation.o: ImageTransformation.cpp.o

.PHONY : ImageTransformation.o

# target to build an object file
ImageTransformation.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageTransformation.cpp.o
.PHONY : ImageTransformation.cpp.o

ImageTransformation.i: ImageTransformation.cpp.i

.PHONY : ImageTransformation.i

# target to preprocess a source file
ImageTransformation.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageTransformation.cpp.i
.PHONY : ImageTransformation.cpp.i

ImageTransformation.s: ImageTransformation.cpp.s

.PHONY : ImageTransformation.s

# target to generate assembly for a file
ImageTransformation.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageTransformation.cpp.s
.PHONY : ImageTransformation.cpp.s

ImageViewBase.o: ImageViewBase.cpp.o

.PHONY : ImageViewBase.o

# target to build an object file
ImageViewBase.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageViewBase.cpp.o
.PHONY : ImageViewBase.cpp.o

ImageViewBase.i: ImageViewBase.cpp.i

.PHONY : ImageViewBase.i

# target to preprocess a source file
ImageViewBase.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageViewBase.cpp.i
.PHONY : ImageViewBase.cpp.i

ImageViewBase.s: ImageViewBase.cpp.s

.PHONY : ImageViewBase.s

# target to generate assembly for a file
ImageViewBase.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ImageViewBase.cpp.s
.PHONY : ImageViewBase.cpp.s

IncompleteThumbnail.o: IncompleteThumbnail.cpp.o

.PHONY : IncompleteThumbnail.o

# target to build an object file
IncompleteThumbnail.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/IncompleteThumbnail.cpp.o
.PHONY : IncompleteThumbnail.cpp.o

IncompleteThumbnail.i: IncompleteThumbnail.cpp.i

.PHONY : IncompleteThumbnail.i

# target to preprocess a source file
IncompleteThumbnail.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/IncompleteThumbnail.cpp.i
.PHONY : IncompleteThumbnail.cpp.i

IncompleteThumbnail.s: IncompleteThumbnail.cpp.s

.PHONY : IncompleteThumbnail.s

# target to generate assembly for a file
IncompleteThumbnail.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/IncompleteThumbnail.cpp.s
.PHONY : IncompleteThumbnail.cpp.s

JpegMetadataLoader.o: JpegMetadataLoader.cpp.o

.PHONY : JpegMetadataLoader.o

# target to build an object file
JpegMetadataLoader.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/JpegMetadataLoader.cpp.o
.PHONY : JpegMetadataLoader.cpp.o

JpegMetadataLoader.i: JpegMetadataLoader.cpp.i

.PHONY : JpegMetadataLoader.i

# target to preprocess a source file
JpegMetadataLoader.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/JpegMetadataLoader.cpp.i
.PHONY : JpegMetadataLoader.cpp.i

JpegMetadataLoader.s: JpegMetadataLoader.cpp.s

.PHONY : JpegMetadataLoader.s

# target to generate assembly for a file
JpegMetadataLoader.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/JpegMetadataLoader.cpp.s
.PHONY : JpegMetadataLoader.cpp.s

LoadFileTask.o: LoadFileTask.cpp.o

.PHONY : LoadFileTask.o

# target to build an object file
LoadFileTask.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/LoadFileTask.cpp.o
.PHONY : LoadFileTask.cpp.o

LoadFileTask.i: LoadFileTask.cpp.i

.PHONY : LoadFileTask.i

# target to preprocess a source file
LoadFileTask.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/LoadFileTask.cpp.i
.PHONY : LoadFileTask.cpp.i

LoadFileTask.s: LoadFileTask.cpp.s

.PHONY : LoadFileTask.s

# target to generate assembly for a file
LoadFileTask.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/LoadFileTask.cpp.s
.PHONY : LoadFileTask.cpp.s

LoadFilesStatusDialog.o: LoadFilesStatusDialog.cpp.o

.PHONY : LoadFilesStatusDialog.o

# target to build an object file
LoadFilesStatusDialog.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/LoadFilesStatusDialog.cpp.o
.PHONY : LoadFilesStatusDialog.cpp.o

LoadFilesStatusDialog.i: LoadFilesStatusDialog.cpp.i

.PHONY : LoadFilesStatusDialog.i

# target to preprocess a source file
LoadFilesStatusDialog.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/LoadFilesStatusDialog.cpp.i
.PHONY : LoadFilesStatusDialog.cpp.i

LoadFilesStatusDialog.s: LoadFilesStatusDialog.cpp.s

.PHONY : LoadFilesStatusDialog.s

# target to generate assembly for a file
LoadFilesStatusDialog.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/LoadFilesStatusDialog.cpp.s
.PHONY : LoadFilesStatusDialog.cpp.s

MainWindow.o: MainWindow.cpp.o

.PHONY : MainWindow.o

# target to build an object file
MainWindow.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/MainWindow.cpp.o
.PHONY : MainWindow.cpp.o

MainWindow.i: MainWindow.cpp.i

.PHONY : MainWindow.i

# target to preprocess a source file
MainWindow.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/MainWindow.cpp.i
.PHONY : MainWindow.cpp.i

MainWindow.s: MainWindow.cpp.s

.PHONY : MainWindow.s

# target to generate assembly for a file
MainWindow.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/MainWindow.cpp.s
.PHONY : MainWindow.cpp.s

NewOpenProjectPanel.o: NewOpenProjectPanel.cpp.o

.PHONY : NewOpenProjectPanel.o

# target to build an object file
NewOpenProjectPanel.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/NewOpenProjectPanel.cpp.o
.PHONY : NewOpenProjectPanel.cpp.o

NewOpenProjectPanel.i: NewOpenProjectPanel.cpp.i

.PHONY : NewOpenProjectPanel.i

# target to preprocess a source file
NewOpenProjectPanel.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/NewOpenProjectPanel.cpp.i
.PHONY : NewOpenProjectPanel.cpp.i

NewOpenProjectPanel.s: NewOpenProjectPanel.cpp.s

.PHONY : NewOpenProjectPanel.s

# target to generate assembly for a file
NewOpenProjectPanel.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/NewOpenProjectPanel.cpp.s
.PHONY : NewOpenProjectPanel.cpp.s

NonOwningWidget.o: NonOwningWidget.cpp.o

.PHONY : NonOwningWidget.o

# target to build an object file
NonOwningWidget.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/NonOwningWidget.cpp.o
.PHONY : NonOwningWidget.cpp.o

NonOwningWidget.i: NonOwningWidget.cpp.i

.PHONY : NonOwningWidget.i

# target to preprocess a source file
NonOwningWidget.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/NonOwningWidget.cpp.i
.PHONY : NonOwningWidget.cpp.i

NonOwningWidget.s: NonOwningWidget.cpp.s

.PHONY : NonOwningWidget.s

# target to generate assembly for a file
NonOwningWidget.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/NonOwningWidget.cpp.s
.PHONY : NonOwningWidget.cpp.s

OpenGLSupport.o: OpenGLSupport.cpp.o

.PHONY : OpenGLSupport.o

# target to build an object file
OpenGLSupport.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/OpenGLSupport.cpp.o
.PHONY : OpenGLSupport.cpp.o

OpenGLSupport.i: OpenGLSupport.cpp.i

.PHONY : OpenGLSupport.i

# target to preprocess a source file
OpenGLSupport.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/OpenGLSupport.cpp.i
.PHONY : OpenGLSupport.cpp.i

OpenGLSupport.s: OpenGLSupport.cpp.s

.PHONY : OpenGLSupport.s

# target to generate assembly for a file
OpenGLSupport.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/OpenGLSupport.cpp.s
.PHONY : OpenGLSupport.cpp.s

OrthogonalRotation.o: OrthogonalRotation.cpp.o

.PHONY : OrthogonalRotation.o

# target to build an object file
OrthogonalRotation.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/OrthogonalRotation.cpp.o
.PHONY : OrthogonalRotation.cpp.o

OrthogonalRotation.i: OrthogonalRotation.cpp.i

.PHONY : OrthogonalRotation.i

# target to preprocess a source file
OrthogonalRotation.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/OrthogonalRotation.cpp.i
.PHONY : OrthogonalRotation.cpp.i

OrthogonalRotation.s: OrthogonalRotation.cpp.s

.PHONY : OrthogonalRotation.s

# target to generate assembly for a file
OrthogonalRotation.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/OrthogonalRotation.cpp.s
.PHONY : OrthogonalRotation.cpp.s

OutOfMemoryDialog.o: OutOfMemoryDialog.cpp.o

.PHONY : OutOfMemoryDialog.o

# target to build an object file
OutOfMemoryDialog.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/OutOfMemoryDialog.cpp.o
.PHONY : OutOfMemoryDialog.cpp.o

OutOfMemoryDialog.i: OutOfMemoryDialog.cpp.i

.PHONY : OutOfMemoryDialog.i

# target to preprocess a source file
OutOfMemoryDialog.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/OutOfMemoryDialog.cpp.i
.PHONY : OutOfMemoryDialog.cpp.i

OutOfMemoryDialog.s: OutOfMemoryDialog.cpp.s

.PHONY : OutOfMemoryDialog.s

# target to generate assembly for a file
OutOfMemoryDialog.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/OutOfMemoryDialog.cpp.s
.PHONY : OutOfMemoryDialog.cpp.s

OutOfMemoryHandler.o: OutOfMemoryHandler.cpp.o

.PHONY : OutOfMemoryHandler.o

# target to build an object file
OutOfMemoryHandler.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/OutOfMemoryHandler.cpp.o
.PHONY : OutOfMemoryHandler.cpp.o

OutOfMemoryHandler.i: OutOfMemoryHandler.cpp.i

.PHONY : OutOfMemoryHandler.i

# target to preprocess a source file
OutOfMemoryHandler.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/OutOfMemoryHandler.cpp.i
.PHONY : OutOfMemoryHandler.cpp.i

OutOfMemoryHandler.s: OutOfMemoryHandler.cpp.s

.PHONY : OutOfMemoryHandler.s

# target to generate assembly for a file
OutOfMemoryHandler.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/OutOfMemoryHandler.cpp.s
.PHONY : OutOfMemoryHandler.cpp.s

OutputFileNameGenerator.o: OutputFileNameGenerator.cpp.o

.PHONY : OutputFileNameGenerator.o

# target to build an object file
OutputFileNameGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/OutputFileNameGenerator.cpp.o
.PHONY : OutputFileNameGenerator.cpp.o

OutputFileNameGenerator.i: OutputFileNameGenerator.cpp.i

.PHONY : OutputFileNameGenerator.i

# target to preprocess a source file
OutputFileNameGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/OutputFileNameGenerator.cpp.i
.PHONY : OutputFileNameGenerator.cpp.i

OutputFileNameGenerator.s: OutputFileNameGenerator.cpp.s

.PHONY : OutputFileNameGenerator.s

# target to generate assembly for a file
OutputFileNameGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/OutputFileNameGenerator.cpp.s
.PHONY : OutputFileNameGenerator.cpp.s

PageId.o: PageId.cpp.o

.PHONY : PageId.o

# target to build an object file
PageId.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageId.cpp.o
.PHONY : PageId.cpp.o

PageId.i: PageId.cpp.i

.PHONY : PageId.i

# target to preprocess a source file
PageId.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageId.cpp.i
.PHONY : PageId.cpp.i

PageId.s: PageId.cpp.s

.PHONY : PageId.s

# target to generate assembly for a file
PageId.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageId.cpp.s
.PHONY : PageId.cpp.s

PageInfo.o: PageInfo.cpp.o

.PHONY : PageInfo.o

# target to build an object file
PageInfo.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageInfo.cpp.o
.PHONY : PageInfo.cpp.o

PageInfo.i: PageInfo.cpp.i

.PHONY : PageInfo.i

# target to preprocess a source file
PageInfo.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageInfo.cpp.i
.PHONY : PageInfo.cpp.i

PageInfo.s: PageInfo.cpp.s

.PHONY : PageInfo.s

# target to generate assembly for a file
PageInfo.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageInfo.cpp.s
.PHONY : PageInfo.cpp.s

PageOrientationPropagator.o: PageOrientationPropagator.cpp.o

.PHONY : PageOrientationPropagator.o

# target to build an object file
PageOrientationPropagator.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageOrientationPropagator.cpp.o
.PHONY : PageOrientationPropagator.cpp.o

PageOrientationPropagator.i: PageOrientationPropagator.cpp.i

.PHONY : PageOrientationPropagator.i

# target to preprocess a source file
PageOrientationPropagator.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageOrientationPropagator.cpp.i
.PHONY : PageOrientationPropagator.cpp.i

PageOrientationPropagator.s: PageOrientationPropagator.cpp.s

.PHONY : PageOrientationPropagator.s

# target to generate assembly for a file
PageOrientationPropagator.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageOrientationPropagator.cpp.s
.PHONY : PageOrientationPropagator.cpp.s

PageRange.o: PageRange.cpp.o

.PHONY : PageRange.o

# target to build an object file
PageRange.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageRange.cpp.o
.PHONY : PageRange.cpp.o

PageRange.i: PageRange.cpp.i

.PHONY : PageRange.i

# target to preprocess a source file
PageRange.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageRange.cpp.i
.PHONY : PageRange.cpp.i

PageRange.s: PageRange.cpp.s

.PHONY : PageRange.s

# target to generate assembly for a file
PageRange.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageRange.cpp.s
.PHONY : PageRange.cpp.s

PageSelectionAccessor.o: PageSelectionAccessor.cpp.o

.PHONY : PageSelectionAccessor.o

# target to build an object file
PageSelectionAccessor.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageSelectionAccessor.cpp.o
.PHONY : PageSelectionAccessor.cpp.o

PageSelectionAccessor.i: PageSelectionAccessor.cpp.i

.PHONY : PageSelectionAccessor.i

# target to preprocess a source file
PageSelectionAccessor.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageSelectionAccessor.cpp.i
.PHONY : PageSelectionAccessor.cpp.i

PageSelectionAccessor.s: PageSelectionAccessor.cpp.s

.PHONY : PageSelectionAccessor.s

# target to generate assembly for a file
PageSelectionAccessor.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageSelectionAccessor.cpp.s
.PHONY : PageSelectionAccessor.cpp.s

PageSequence.o: PageSequence.cpp.o

.PHONY : PageSequence.o

# target to build an object file
PageSequence.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageSequence.cpp.o
.PHONY : PageSequence.cpp.o

PageSequence.i: PageSequence.cpp.i

.PHONY : PageSequence.i

# target to preprocess a source file
PageSequence.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageSequence.cpp.i
.PHONY : PageSequence.cpp.i

PageSequence.s: PageSequence.cpp.s

.PHONY : PageSequence.s

# target to generate assembly for a file
PageSequence.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PageSequence.cpp.s
.PHONY : PageSequence.cpp.s

PhysicalTransformation.o: PhysicalTransformation.cpp.o

.PHONY : PhysicalTransformation.o

# target to build an object file
PhysicalTransformation.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PhysicalTransformation.cpp.o
.PHONY : PhysicalTransformation.cpp.o

PhysicalTransformation.i: PhysicalTransformation.cpp.i

.PHONY : PhysicalTransformation.i

# target to preprocess a source file
PhysicalTransformation.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PhysicalTransformation.cpp.i
.PHONY : PhysicalTransformation.cpp.i

PhysicalTransformation.s: PhysicalTransformation.cpp.s

.PHONY : PhysicalTransformation.s

# target to generate assembly for a file
PhysicalTransformation.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PhysicalTransformation.cpp.s
.PHONY : PhysicalTransformation.cpp.s

PixmapRenderer.o: PixmapRenderer.cpp.o

.PHONY : PixmapRenderer.o

# target to build an object file
PixmapRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PixmapRenderer.cpp.o
.PHONY : PixmapRenderer.cpp.o

PixmapRenderer.i: PixmapRenderer.cpp.i

.PHONY : PixmapRenderer.i

# target to preprocess a source file
PixmapRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PixmapRenderer.cpp.i
.PHONY : PixmapRenderer.cpp.i

PixmapRenderer.s: PixmapRenderer.cpp.s

.PHONY : PixmapRenderer.s

# target to generate assembly for a file
PixmapRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PixmapRenderer.cpp.s
.PHONY : PixmapRenderer.cpp.s

PngMetadataLoader.o: PngMetadataLoader.cpp.o

.PHONY : PngMetadataLoader.o

# target to build an object file
PngMetadataLoader.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PngMetadataLoader.cpp.o
.PHONY : PngMetadataLoader.cpp.o

PngMetadataLoader.i: PngMetadataLoader.cpp.i

.PHONY : PngMetadataLoader.i

# target to preprocess a source file
PngMetadataLoader.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PngMetadataLoader.cpp.i
.PHONY : PngMetadataLoader.cpp.i

PngMetadataLoader.s: PngMetadataLoader.cpp.s

.PHONY : PngMetadataLoader.s

# target to generate assembly for a file
PngMetadataLoader.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/PngMetadataLoader.cpp.s
.PHONY : PngMetadataLoader.cpp.s

ProcessingIndicationWidget.o: ProcessingIndicationWidget.cpp.o

.PHONY : ProcessingIndicationWidget.o

# target to build an object file
ProcessingIndicationWidget.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ProcessingIndicationWidget.cpp.o
.PHONY : ProcessingIndicationWidget.cpp.o

ProcessingIndicationWidget.i: ProcessingIndicationWidget.cpp.i

.PHONY : ProcessingIndicationWidget.i

# target to preprocess a source file
ProcessingIndicationWidget.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ProcessingIndicationWidget.cpp.i
.PHONY : ProcessingIndicationWidget.cpp.i

ProcessingIndicationWidget.s: ProcessingIndicationWidget.cpp.s

.PHONY : ProcessingIndicationWidget.s

# target to generate assembly for a file
ProcessingIndicationWidget.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ProcessingIndicationWidget.cpp.s
.PHONY : ProcessingIndicationWidget.cpp.s

ProcessingTaskQueue.o: ProcessingTaskQueue.cpp.o

.PHONY : ProcessingTaskQueue.o

# target to build an object file
ProcessingTaskQueue.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ProcessingTaskQueue.cpp.o
.PHONY : ProcessingTaskQueue.cpp.o

ProcessingTaskQueue.i: ProcessingTaskQueue.cpp.i

.PHONY : ProcessingTaskQueue.i

# target to preprocess a source file
ProcessingTaskQueue.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ProcessingTaskQueue.cpp.i
.PHONY : ProcessingTaskQueue.cpp.i

ProcessingTaskQueue.s: ProcessingTaskQueue.cpp.s

.PHONY : ProcessingTaskQueue.s

# target to generate assembly for a file
ProcessingTaskQueue.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ProcessingTaskQueue.cpp.s
.PHONY : ProcessingTaskQueue.cpp.s

ProjectCreationContext.o: ProjectCreationContext.cpp.o

.PHONY : ProjectCreationContext.o

# target to build an object file
ProjectCreationContext.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/ProjectCreationContext.cpp.o
.PHONY : ProjectCreationContext.cpp.o

ProjectCreationContext.i: ProjectCreationContext.cpp.i

.PHONY : ProjectCreationContext.i

# target to preprocess a source file
ProjectCreationContext.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/ProjectCreationContext.cpp.i
.PHONY : ProjectCreationContext.cpp.i

ProjectCreationContext.s: ProjectCreationContext.cpp.s

.PHONY : ProjectCreationContext.s

# target to generate assembly for a file
ProjectCreationContext.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/ProjectCreationContext.cpp.s
.PHONY : ProjectCreationContext.cpp.s

ProjectFilesDialog.o: ProjectFilesDialog.cpp.o

.PHONY : ProjectFilesDialog.o

# target to build an object file
ProjectFilesDialog.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/ProjectFilesDialog.cpp.o
.PHONY : ProjectFilesDialog.cpp.o

ProjectFilesDialog.i: ProjectFilesDialog.cpp.i

.PHONY : ProjectFilesDialog.i

# target to preprocess a source file
ProjectFilesDialog.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/ProjectFilesDialog.cpp.i
.PHONY : ProjectFilesDialog.cpp.i

ProjectFilesDialog.s: ProjectFilesDialog.cpp.s

.PHONY : ProjectFilesDialog.s

# target to generate assembly for a file
ProjectFilesDialog.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/ProjectFilesDialog.cpp.s
.PHONY : ProjectFilesDialog.cpp.s

ProjectOpeningContext.o: ProjectOpeningContext.cpp.o

.PHONY : ProjectOpeningContext.o

# target to build an object file
ProjectOpeningContext.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/ProjectOpeningContext.cpp.o
.PHONY : ProjectOpeningContext.cpp.o

ProjectOpeningContext.i: ProjectOpeningContext.cpp.i

.PHONY : ProjectOpeningContext.i

# target to preprocess a source file
ProjectOpeningContext.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/ProjectOpeningContext.cpp.i
.PHONY : ProjectOpeningContext.cpp.i

ProjectOpeningContext.s: ProjectOpeningContext.cpp.s

.PHONY : ProjectOpeningContext.s

# target to generate assembly for a file
ProjectOpeningContext.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/ProjectOpeningContext.cpp.s
.PHONY : ProjectOpeningContext.cpp.s

ProjectPages.o: ProjectPages.cpp.o

.PHONY : ProjectPages.o

# target to build an object file
ProjectPages.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ProjectPages.cpp.o
.PHONY : ProjectPages.cpp.o

ProjectPages.i: ProjectPages.cpp.i

.PHONY : ProjectPages.i

# target to preprocess a source file
ProjectPages.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ProjectPages.cpp.i
.PHONY : ProjectPages.cpp.i

ProjectPages.s: ProjectPages.cpp.s

.PHONY : ProjectPages.s

# target to generate assembly for a file
ProjectPages.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ProjectPages.cpp.s
.PHONY : ProjectPages.cpp.s

ProjectReader.o: ProjectReader.cpp.o

.PHONY : ProjectReader.o

# target to build an object file
ProjectReader.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ProjectReader.cpp.o
.PHONY : ProjectReader.cpp.o

ProjectReader.i: ProjectReader.cpp.i

.PHONY : ProjectReader.i

# target to preprocess a source file
ProjectReader.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ProjectReader.cpp.i
.PHONY : ProjectReader.cpp.i

ProjectReader.s: ProjectReader.cpp.s

.PHONY : ProjectReader.s

# target to generate assembly for a file
ProjectReader.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ProjectReader.cpp.s
.PHONY : ProjectReader.cpp.s

ProjectWriter.o: ProjectWriter.cpp.o

.PHONY : ProjectWriter.o

# target to build an object file
ProjectWriter.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ProjectWriter.cpp.o
.PHONY : ProjectWriter.cpp.o

ProjectWriter.i: ProjectWriter.cpp.i

.PHONY : ProjectWriter.i

# target to preprocess a source file
ProjectWriter.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ProjectWriter.cpp.i
.PHONY : ProjectWriter.cpp.i

ProjectWriter.s: ProjectWriter.cpp.s

.PHONY : ProjectWriter.s

# target to generate assembly for a file
ProjectWriter.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ProjectWriter.cpp.s
.PHONY : ProjectWriter.cpp.s

RecentProjects.o: RecentProjects.cpp.o

.PHONY : RecentProjects.o

# target to build an object file
RecentProjects.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/RecentProjects.cpp.o
.PHONY : RecentProjects.cpp.o

RecentProjects.i: RecentProjects.cpp.i

.PHONY : RecentProjects.i

# target to preprocess a source file
RecentProjects.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/RecentProjects.cpp.i
.PHONY : RecentProjects.cpp.i

RecentProjects.s: RecentProjects.cpp.s

.PHONY : RecentProjects.s

# target to generate assembly for a file
RecentProjects.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/RecentProjects.cpp.s
.PHONY : RecentProjects.cpp.s

RelinkablePath.o: RelinkablePath.cpp.o

.PHONY : RelinkablePath.o

# target to build an object file
RelinkablePath.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/RelinkablePath.cpp.o
.PHONY : RelinkablePath.cpp.o

RelinkablePath.i: RelinkablePath.cpp.i

.PHONY : RelinkablePath.i

# target to preprocess a source file
RelinkablePath.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/RelinkablePath.cpp.i
.PHONY : RelinkablePath.cpp.i

RelinkablePath.s: RelinkablePath.cpp.s

.PHONY : RelinkablePath.s

# target to generate assembly for a file
RelinkablePath.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/RelinkablePath.cpp.s
.PHONY : RelinkablePath.cpp.s

RelinkablePathVisualization.o: RelinkablePathVisualization.cpp.o

.PHONY : RelinkablePathVisualization.o

# target to build an object file
RelinkablePathVisualization.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/RelinkablePathVisualization.cpp.o
.PHONY : RelinkablePathVisualization.cpp.o

RelinkablePathVisualization.i: RelinkablePathVisualization.cpp.i

.PHONY : RelinkablePathVisualization.i

# target to preprocess a source file
RelinkablePathVisualization.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/RelinkablePathVisualization.cpp.i
.PHONY : RelinkablePathVisualization.cpp.i

RelinkablePathVisualization.s: RelinkablePathVisualization.cpp.s

.PHONY : RelinkablePathVisualization.s

# target to generate assembly for a file
RelinkablePathVisualization.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/RelinkablePathVisualization.cpp.s
.PHONY : RelinkablePathVisualization.cpp.s

RelinkingDialog.o: RelinkingDialog.cpp.o

.PHONY : RelinkingDialog.o

# target to build an object file
RelinkingDialog.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/RelinkingDialog.cpp.o
.PHONY : RelinkingDialog.cpp.o

RelinkingDialog.i: RelinkingDialog.cpp.i

.PHONY : RelinkingDialog.i

# target to preprocess a source file
RelinkingDialog.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/RelinkingDialog.cpp.i
.PHONY : RelinkingDialog.cpp.i

RelinkingDialog.s: RelinkingDialog.cpp.s

.PHONY : RelinkingDialog.s

# target to generate assembly for a file
RelinkingDialog.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/RelinkingDialog.cpp.s
.PHONY : RelinkingDialog.cpp.s

RelinkingListView.o: RelinkingListView.cpp.o

.PHONY : RelinkingListView.o

# target to build an object file
RelinkingListView.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/RelinkingListView.cpp.o
.PHONY : RelinkingListView.cpp.o

RelinkingListView.i: RelinkingListView.cpp.i

.PHONY : RelinkingListView.i

# target to preprocess a source file
RelinkingListView.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/RelinkingListView.cpp.i
.PHONY : RelinkingListView.cpp.i

RelinkingListView.s: RelinkingListView.cpp.s

.PHONY : RelinkingListView.s

# target to generate assembly for a file
RelinkingListView.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/RelinkingListView.cpp.s
.PHONY : RelinkingListView.cpp.s

RelinkingModel.o: RelinkingModel.cpp.o

.PHONY : RelinkingModel.o

# target to build an object file
RelinkingModel.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/RelinkingModel.cpp.o
.PHONY : RelinkingModel.cpp.o

RelinkingModel.i: RelinkingModel.cpp.i

.PHONY : RelinkingModel.i

# target to preprocess a source file
RelinkingModel.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/RelinkingModel.cpp.i
.PHONY : RelinkingModel.cpp.i

RelinkingModel.s: RelinkingModel.cpp.s

.PHONY : RelinkingModel.s

# target to generate assembly for a file
RelinkingModel.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/RelinkingModel.cpp.s
.PHONY : RelinkingModel.cpp.s

RelinkingSortingModel.o: RelinkingSortingModel.cpp.o

.PHONY : RelinkingSortingModel.o

# target to build an object file
RelinkingSortingModel.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/RelinkingSortingModel.cpp.o
.PHONY : RelinkingSortingModel.cpp.o

RelinkingSortingModel.i: RelinkingSortingModel.cpp.i

.PHONY : RelinkingSortingModel.i

# target to preprocess a source file
RelinkingSortingModel.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/RelinkingSortingModel.cpp.i
.PHONY : RelinkingSortingModel.cpp.i

RelinkingSortingModel.s: RelinkingSortingModel.cpp.s

.PHONY : RelinkingSortingModel.s

# target to generate assembly for a file
RelinkingSortingModel.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/RelinkingSortingModel.cpp.s
.PHONY : RelinkingSortingModel.cpp.s

SelectedPage.o: SelectedPage.cpp.o

.PHONY : SelectedPage.o

# target to build an object file
SelectedPage.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/SelectedPage.cpp.o
.PHONY : SelectedPage.cpp.o

SelectedPage.i: SelectedPage.cpp.i

.PHONY : SelectedPage.i

# target to preprocess a source file
SelectedPage.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/SelectedPage.cpp.i
.PHONY : SelectedPage.cpp.i

SelectedPage.s: SelectedPage.cpp.s

.PHONY : SelectedPage.s

# target to generate assembly for a file
SelectedPage.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/SelectedPage.cpp.s
.PHONY : SelectedPage.cpp.s

SettingsDialog.o: SettingsDialog.cpp.o

.PHONY : SettingsDialog.o

# target to build an object file
SettingsDialog.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/SettingsDialog.cpp.o
.PHONY : SettingsDialog.cpp.o

SettingsDialog.i: SettingsDialog.cpp.i

.PHONY : SettingsDialog.i

# target to preprocess a source file
SettingsDialog.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/SettingsDialog.cpp.i
.PHONY : SettingsDialog.cpp.i

SettingsDialog.s: SettingsDialog.cpp.s

.PHONY : SettingsDialog.s

# target to generate assembly for a file
SettingsDialog.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/SettingsDialog.cpp.s
.PHONY : SettingsDialog.cpp.s

SkinnedButton.o: SkinnedButton.cpp.o

.PHONY : SkinnedButton.o

# target to build an object file
SkinnedButton.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/SkinnedButton.cpp.o
.PHONY : SkinnedButton.cpp.o

SkinnedButton.i: SkinnedButton.cpp.i

.PHONY : SkinnedButton.i

# target to preprocess a source file
SkinnedButton.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/SkinnedButton.cpp.i
.PHONY : SkinnedButton.cpp.i

SkinnedButton.s: SkinnedButton.cpp.s

.PHONY : SkinnedButton.s

# target to generate assembly for a file
SkinnedButton.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/SkinnedButton.cpp.s
.PHONY : SkinnedButton.cpp.s

SmartFilenameOrdering.o: SmartFilenameOrdering.cpp.o

.PHONY : SmartFilenameOrdering.o

# target to build an object file
SmartFilenameOrdering.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/SmartFilenameOrdering.cpp.o
.PHONY : SmartFilenameOrdering.cpp.o

SmartFilenameOrdering.i: SmartFilenameOrdering.cpp.i

.PHONY : SmartFilenameOrdering.i

# target to preprocess a source file
SmartFilenameOrdering.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/SmartFilenameOrdering.cpp.i
.PHONY : SmartFilenameOrdering.cpp.i

SmartFilenameOrdering.s: SmartFilenameOrdering.cpp.s

.PHONY : SmartFilenameOrdering.s

# target to generate assembly for a file
SmartFilenameOrdering.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/SmartFilenameOrdering.cpp.s
.PHONY : SmartFilenameOrdering.cpp.s

StageListView.o: StageListView.cpp.o

.PHONY : StageListView.o

# target to build an object file
StageListView.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/StageListView.cpp.o
.PHONY : StageListView.cpp.o

StageListView.i: StageListView.cpp.i

.PHONY : StageListView.i

# target to preprocess a source file
StageListView.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/StageListView.cpp.i
.PHONY : StageListView.cpp.i

StageListView.s: StageListView.cpp.s

.PHONY : StageListView.s

# target to generate assembly for a file
StageListView.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/StageListView.cpp.s
.PHONY : StageListView.cpp.s

StageSequence.o: StageSequence.cpp.o

.PHONY : StageSequence.o

# target to build an object file
StageSequence.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/StageSequence.cpp.o
.PHONY : StageSequence.cpp.o

StageSequence.i: StageSequence.cpp.i

.PHONY : StageSequence.i

# target to preprocess a source file
StageSequence.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/StageSequence.cpp.i
.PHONY : StageSequence.cpp.i

StageSequence.s: StageSequence.cpp.s

.PHONY : StageSequence.s

# target to generate assembly for a file
StageSequence.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/StageSequence.cpp.s
.PHONY : StageSequence.cpp.s

SystemLoadWidget.o: SystemLoadWidget.cpp.o

.PHONY : SystemLoadWidget.o

# target to build an object file
SystemLoadWidget.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/SystemLoadWidget.cpp.o
.PHONY : SystemLoadWidget.cpp.o

SystemLoadWidget.i: SystemLoadWidget.cpp.i

.PHONY : SystemLoadWidget.i

# target to preprocess a source file
SystemLoadWidget.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/SystemLoadWidget.cpp.i
.PHONY : SystemLoadWidget.cpp.i

SystemLoadWidget.s: SystemLoadWidget.cpp.s

.PHONY : SystemLoadWidget.s

# target to generate assembly for a file
SystemLoadWidget.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/SystemLoadWidget.cpp.s
.PHONY : SystemLoadWidget.cpp.s

TabbedDebugImages.o: TabbedDebugImages.cpp.o

.PHONY : TabbedDebugImages.o

# target to build an object file
TabbedDebugImages.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/TabbedDebugImages.cpp.o
.PHONY : TabbedDebugImages.cpp.o

TabbedDebugImages.i: TabbedDebugImages.cpp.i

.PHONY : TabbedDebugImages.i

# target to preprocess a source file
TabbedDebugImages.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/TabbedDebugImages.cpp.i
.PHONY : TabbedDebugImages.cpp.i

TabbedDebugImages.s: TabbedDebugImages.cpp.s

.PHONY : TabbedDebugImages.s

# target to generate assembly for a file
TabbedDebugImages.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/TabbedDebugImages.cpp.s
.PHONY : TabbedDebugImages.cpp.s

ThreadPriority.o: ThreadPriority.cpp.o

.PHONY : ThreadPriority.o

# target to build an object file
ThreadPriority.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ThreadPriority.cpp.o
.PHONY : ThreadPriority.cpp.o

ThreadPriority.i: ThreadPriority.cpp.i

.PHONY : ThreadPriority.i

# target to preprocess a source file
ThreadPriority.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ThreadPriority.cpp.i
.PHONY : ThreadPriority.cpp.i

ThreadPriority.s: ThreadPriority.cpp.s

.PHONY : ThreadPriority.s

# target to generate assembly for a file
ThreadPriority.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ThreadPriority.cpp.s
.PHONY : ThreadPriority.cpp.s

ThumbnailBase.o: ThumbnailBase.cpp.o

.PHONY : ThumbnailBase.o

# target to build an object file
ThumbnailBase.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ThumbnailBase.cpp.o
.PHONY : ThumbnailBase.cpp.o

ThumbnailBase.i: ThumbnailBase.cpp.i

.PHONY : ThumbnailBase.i

# target to preprocess a source file
ThumbnailBase.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ThumbnailBase.cpp.i
.PHONY : ThumbnailBase.cpp.i

ThumbnailBase.s: ThumbnailBase.cpp.s

.PHONY : ThumbnailBase.s

# target to generate assembly for a file
ThumbnailBase.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ThumbnailBase.cpp.s
.PHONY : ThumbnailBase.cpp.s

ThumbnailFactory.o: ThumbnailFactory.cpp.o

.PHONY : ThumbnailFactory.o

# target to build an object file
ThumbnailFactory.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ThumbnailFactory.cpp.o
.PHONY : ThumbnailFactory.cpp.o

ThumbnailFactory.i: ThumbnailFactory.cpp.i

.PHONY : ThumbnailFactory.i

# target to preprocess a source file
ThumbnailFactory.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ThumbnailFactory.cpp.i
.PHONY : ThumbnailFactory.cpp.i

ThumbnailFactory.s: ThumbnailFactory.cpp.s

.PHONY : ThumbnailFactory.s

# target to generate assembly for a file
ThumbnailFactory.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ThumbnailFactory.cpp.s
.PHONY : ThumbnailFactory.cpp.s

ThumbnailPixmapCache.o: ThumbnailPixmapCache.cpp.o

.PHONY : ThumbnailPixmapCache.o

# target to build an object file
ThumbnailPixmapCache.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ThumbnailPixmapCache.cpp.o
.PHONY : ThumbnailPixmapCache.cpp.o

ThumbnailPixmapCache.i: ThumbnailPixmapCache.cpp.i

.PHONY : ThumbnailPixmapCache.i

# target to preprocess a source file
ThumbnailPixmapCache.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ThumbnailPixmapCache.cpp.i
.PHONY : ThumbnailPixmapCache.cpp.i

ThumbnailPixmapCache.s: ThumbnailPixmapCache.cpp.s

.PHONY : ThumbnailPixmapCache.s

# target to generate assembly for a file
ThumbnailPixmapCache.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/ThumbnailPixmapCache.cpp.s
.PHONY : ThumbnailPixmapCache.cpp.s

ThumbnailSequence.o: ThumbnailSequence.cpp.o

.PHONY : ThumbnailSequence.o

# target to build an object file
ThumbnailSequence.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/ThumbnailSequence.cpp.o
.PHONY : ThumbnailSequence.cpp.o

ThumbnailSequence.i: ThumbnailSequence.cpp.i

.PHONY : ThumbnailSequence.i

# target to preprocess a source file
ThumbnailSequence.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/ThumbnailSequence.cpp.i
.PHONY : ThumbnailSequence.cpp.i

ThumbnailSequence.s: ThumbnailSequence.cpp.s

.PHONY : ThumbnailSequence.s

# target to generate assembly for a file
ThumbnailSequence.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/ThumbnailSequence.cpp.s
.PHONY : ThumbnailSequence.cpp.s

TiffMetadataLoader.o: TiffMetadataLoader.cpp.o

.PHONY : TiffMetadataLoader.o

# target to build an object file
TiffMetadataLoader.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/TiffMetadataLoader.cpp.o
.PHONY : TiffMetadataLoader.cpp.o

TiffMetadataLoader.i: TiffMetadataLoader.cpp.i

.PHONY : TiffMetadataLoader.i

# target to preprocess a source file
TiffMetadataLoader.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/TiffMetadataLoader.cpp.i
.PHONY : TiffMetadataLoader.cpp.i

TiffMetadataLoader.s: TiffMetadataLoader.cpp.s

.PHONY : TiffMetadataLoader.s

# target to generate assembly for a file
TiffMetadataLoader.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/TiffMetadataLoader.cpp.s
.PHONY : TiffMetadataLoader.cpp.s

TiffReader.o: TiffReader.cpp.o

.PHONY : TiffReader.o

# target to build an object file
TiffReader.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/TiffReader.cpp.o
.PHONY : TiffReader.cpp.o

TiffReader.i: TiffReader.cpp.i

.PHONY : TiffReader.i

# target to preprocess a source file
TiffReader.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/TiffReader.cpp.i
.PHONY : TiffReader.cpp.i

TiffReader.s: TiffReader.cpp.s

.PHONY : TiffReader.s

# target to generate assembly for a file
TiffReader.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/TiffReader.cpp.s
.PHONY : TiffReader.cpp.s

TiffWriter.o: TiffWriter.cpp.o

.PHONY : TiffWriter.o

# target to build an object file
TiffWriter.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/TiffWriter.cpp.o
.PHONY : TiffWriter.cpp.o

TiffWriter.i: TiffWriter.cpp.i

.PHONY : TiffWriter.i

# target to preprocess a source file
TiffWriter.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/TiffWriter.cpp.i
.PHONY : TiffWriter.cpp.i

TiffWriter.s: TiffWriter.cpp.s

.PHONY : TiffWriter.s

# target to generate assembly for a file
TiffWriter.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/TiffWriter.cpp.s
.PHONY : TiffWriter.cpp.s

Utils.o: Utils.cpp.o

.PHONY : Utils.o

# target to build an object file
Utils.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/Utils.cpp.o
.PHONY : Utils.cpp.o

Utils.i: Utils.cpp.i

.PHONY : Utils.i

# target to preprocess a source file
Utils.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/Utils.cpp.i
.PHONY : Utils.cpp.i

Utils.s: Utils.cpp.s

.PHONY : Utils.s

# target to generate assembly for a file
Utils.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/Utils.cpp.s
.PHONY : Utils.cpp.s

WorkerThread.o: WorkerThread.cpp.o

.PHONY : WorkerThread.o

# target to build an object file
WorkerThread.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/WorkerThread.cpp.o
.PHONY : WorkerThread.cpp.o

WorkerThread.i: WorkerThread.cpp.i

.PHONY : WorkerThread.i

# target to preprocess a source file
WorkerThread.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/WorkerThread.cpp.i
.PHONY : WorkerThread.cpp.i

WorkerThread.s: WorkerThread.cpp.s

.PHONY : WorkerThread.s

# target to generate assembly for a file
WorkerThread.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/WorkerThread.cpp.s
.PHONY : WorkerThread.cpp.s

XmlMarshaller.o: XmlMarshaller.cpp.o

.PHONY : XmlMarshaller.o

# target to build an object file
XmlMarshaller.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/XmlMarshaller.cpp.o
.PHONY : XmlMarshaller.cpp.o

XmlMarshaller.i: XmlMarshaller.cpp.i

.PHONY : XmlMarshaller.i

# target to preprocess a source file
XmlMarshaller.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/XmlMarshaller.cpp.i
.PHONY : XmlMarshaller.cpp.i

XmlMarshaller.s: XmlMarshaller.cpp.s

.PHONY : XmlMarshaller.s

# target to generate assembly for a file
XmlMarshaller.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/XmlMarshaller.cpp.s
.PHONY : XmlMarshaller.cpp.s

XmlUnmarshaller.o: XmlUnmarshaller.cpp.o

.PHONY : XmlUnmarshaller.o

# target to build an object file
XmlUnmarshaller.cpp.o:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/XmlUnmarshaller.cpp.o
.PHONY : XmlUnmarshaller.cpp.o

XmlUnmarshaller.i: XmlUnmarshaller.cpp.i

.PHONY : XmlUnmarshaller.i

# target to preprocess a source file
XmlUnmarshaller.cpp.i:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/XmlUnmarshaller.cpp.i
.PHONY : XmlUnmarshaller.cpp.i

XmlUnmarshaller.s: XmlUnmarshaller.cpp.s

.PHONY : XmlUnmarshaller.s

# target to generate assembly for a file
XmlUnmarshaller.cpp.s:
	$(MAKE) -f CMakeFiles/stcore.dir/build.make CMakeFiles/stcore.dir/XmlUnmarshaller.cpp.s
.PHONY : XmlUnmarshaller.cpp.s

main-cli.o: main-cli.cpp.o

.PHONY : main-cli.o

# target to build an object file
main-cli.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor-cli.dir/build.make CMakeFiles/scantailor-cli.dir/main-cli.cpp.o
.PHONY : main-cli.cpp.o

main-cli.i: main-cli.cpp.i

.PHONY : main-cli.i

# target to preprocess a source file
main-cli.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor-cli.dir/build.make CMakeFiles/scantailor-cli.dir/main-cli.cpp.i
.PHONY : main-cli.cpp.i

main-cli.s: main-cli.cpp.s

.PHONY : main-cli.s

# target to generate assembly for a file
main-cli.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor-cli.dir/build.make CMakeFiles/scantailor-cli.dir/main-cli.cpp.s
.PHONY : main-cli.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/main.cpp.s
.PHONY : main.cpp.s

qrc_resources.o: qrc_resources.cxx.o

.PHONY : qrc_resources.o

# target to build an object file
qrc_resources.cxx.o:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/qrc_resources.cxx.o
.PHONY : qrc_resources.cxx.o

qrc_resources.i: qrc_resources.cxx.i

.PHONY : qrc_resources.i

# target to preprocess a source file
qrc_resources.cxx.i:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/qrc_resources.cxx.i
.PHONY : qrc_resources.cxx.i

qrc_resources.s: qrc_resources.cxx.s

.PHONY : qrc_resources.s

# target to generate assembly for a file
qrc_resources.cxx.s:
	$(MAKE) -f CMakeFiles/scantailor.dir/build.make CMakeFiles/scantailor.dir/qrc_resources.cxx.s
.PHONY : qrc_resources.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... package"
	@echo "... edit_cache"
	@echo "... toplevel_ui_sources"
	@echo "... test"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... compile_translations"
	@echo "... update_translations"
	@echo "... scantailor-cli"
	@echo "... scantailor"
	@echo "... rebuild_cache"
	@echo "... package_source"
	@echo "... stcore"
	@echo "... dewarping"
	@echo "... foundation"
	@echo "... math"
	@echo "... spfit_tests"
	@echo "... adiff_tests"
	@echo "... imageproc"
	@echo "... imageproc_tests"
	@echo "... interaction"
	@echo "... zones"
	@echo "... tests"
	@echo "... fix_orientation"
	@echo "... page_split"
	@echo "... deskew"
	@echo "... select_content"
	@echo "... page_layout"
	@echo "... output"
	@echo "... Application.o"
	@echo "... Application.i"
	@echo "... Application.s"
	@echo "... AtomicFileOverwriter.o"
	@echo "... AtomicFileOverwriter.i"
	@echo "... AtomicFileOverwriter.s"
	@echo "... BackgroundExecutor.o"
	@echo "... BackgroundExecutor.i"
	@echo "... BackgroundExecutor.s"
	@echo "... BackgroundTask.o"
	@echo "... BackgroundTask.i"
	@echo "... BackgroundTask.s"
	@echo "... BasicImageView.o"
	@echo "... BasicImageView.i"
	@echo "... BasicImageView.s"
	@echo "... BubbleAnimation.o"
	@echo "... BubbleAnimation.i"
	@echo "... BubbleAnimation.s"
	@echo "... CommandLine.o"
	@echo "... CommandLine.i"
	@echo "... CommandLine.s"
	@echo "... ConsoleBatch.o"
	@echo "... ConsoleBatch.i"
	@echo "... ConsoleBatch.s"
	@echo "... ContentBoxPropagator.o"
	@echo "... ContentBoxPropagator.i"
	@echo "... ContentBoxPropagator.s"
	@echo "... ContentSpanFinder.o"
	@echo "... ContentSpanFinder.i"
	@echo "... ContentSpanFinder.s"
	@echo "... DebugImageView.o"
	@echo "... DebugImageView.i"
	@echo "... DebugImageView.s"
	@echo "... DebugImages.o"
	@echo "... DebugImages.i"
	@echo "... DebugImages.s"
	@echo "... Despeckle.o"
	@echo "... Despeckle.i"
	@echo "... Despeckle.s"
	@echo "... Dpi.o"
	@echo "... Dpi.i"
	@echo "... Dpi.s"
	@echo "... Dpm.o"
	@echo "... Dpm.i"
	@echo "... Dpm.s"
	@echo "... ErrorWidget.o"
	@echo "... ErrorWidget.i"
	@echo "... ErrorWidget.s"
	@echo "... EstimateBackground.o"
	@echo "... EstimateBackground.i"
	@echo "... EstimateBackground.s"
	@echo "... ExportDialog.o"
	@echo "... ExportDialog.i"
	@echo "... ExportDialog.s"
	@echo "... FileNameDisambiguator.o"
	@echo "... FileNameDisambiguator.i"
	@echo "... FileNameDisambiguator.s"
	@echo "... FilterData.o"
	@echo "... FilterData.i"
	@echo "... FilterData.s"
	@echo "... FilterOptionsWidget.o"
	@echo "... FilterOptionsWidget.i"
	@echo "... FilterOptionsWidget.s"
	@echo "... FixDpiDialog.o"
	@echo "... FixDpiDialog.i"
	@echo "... FixDpiDialog.s"
	@echo "... ImageFileInfo.o"
	@echo "... ImageFileInfo.i"
	@echo "... ImageFileInfo.s"
	@echo "... ImageId.o"
	@echo "... ImageId.i"
	@echo "... ImageId.s"
	@echo "... ImageInfo.o"
	@echo "... ImageInfo.i"
	@echo "... ImageInfo.s"
	@echo "... ImageLoader.o"
	@echo "... ImageLoader.i"
	@echo "... ImageLoader.s"
	@echo "... ImageMetadata.o"
	@echo "... ImageMetadata.i"
	@echo "... ImageMetadata.s"
	@echo "... ImageMetadataLoader.o"
	@echo "... ImageMetadataLoader.i"
	@echo "... ImageMetadataLoader.s"
	@echo "... ImageTransformation.o"
	@echo "... ImageTransformation.i"
	@echo "... ImageTransformation.s"
	@echo "... ImageViewBase.o"
	@echo "... ImageViewBase.i"
	@echo "... ImageViewBase.s"
	@echo "... IncompleteThumbnail.o"
	@echo "... IncompleteThumbnail.i"
	@echo "... IncompleteThumbnail.s"
	@echo "... JpegMetadataLoader.o"
	@echo "... JpegMetadataLoader.i"
	@echo "... JpegMetadataLoader.s"
	@echo "... LoadFileTask.o"
	@echo "... LoadFileTask.i"
	@echo "... LoadFileTask.s"
	@echo "... LoadFilesStatusDialog.o"
	@echo "... LoadFilesStatusDialog.i"
	@echo "... LoadFilesStatusDialog.s"
	@echo "... MainWindow.o"
	@echo "... MainWindow.i"
	@echo "... MainWindow.s"
	@echo "... NewOpenProjectPanel.o"
	@echo "... NewOpenProjectPanel.i"
	@echo "... NewOpenProjectPanel.s"
	@echo "... NonOwningWidget.o"
	@echo "... NonOwningWidget.i"
	@echo "... NonOwningWidget.s"
	@echo "... OpenGLSupport.o"
	@echo "... OpenGLSupport.i"
	@echo "... OpenGLSupport.s"
	@echo "... OrthogonalRotation.o"
	@echo "... OrthogonalRotation.i"
	@echo "... OrthogonalRotation.s"
	@echo "... OutOfMemoryDialog.o"
	@echo "... OutOfMemoryDialog.i"
	@echo "... OutOfMemoryDialog.s"
	@echo "... OutOfMemoryHandler.o"
	@echo "... OutOfMemoryHandler.i"
	@echo "... OutOfMemoryHandler.s"
	@echo "... OutputFileNameGenerator.o"
	@echo "... OutputFileNameGenerator.i"
	@echo "... OutputFileNameGenerator.s"
	@echo "... PageId.o"
	@echo "... PageId.i"
	@echo "... PageId.s"
	@echo "... PageInfo.o"
	@echo "... PageInfo.i"
	@echo "... PageInfo.s"
	@echo "... PageOrientationPropagator.o"
	@echo "... PageOrientationPropagator.i"
	@echo "... PageOrientationPropagator.s"
	@echo "... PageRange.o"
	@echo "... PageRange.i"
	@echo "... PageRange.s"
	@echo "... PageSelectionAccessor.o"
	@echo "... PageSelectionAccessor.i"
	@echo "... PageSelectionAccessor.s"
	@echo "... PageSequence.o"
	@echo "... PageSequence.i"
	@echo "... PageSequence.s"
	@echo "... PhysicalTransformation.o"
	@echo "... PhysicalTransformation.i"
	@echo "... PhysicalTransformation.s"
	@echo "... PixmapRenderer.o"
	@echo "... PixmapRenderer.i"
	@echo "... PixmapRenderer.s"
	@echo "... PngMetadataLoader.o"
	@echo "... PngMetadataLoader.i"
	@echo "... PngMetadataLoader.s"
	@echo "... ProcessingIndicationWidget.o"
	@echo "... ProcessingIndicationWidget.i"
	@echo "... ProcessingIndicationWidget.s"
	@echo "... ProcessingTaskQueue.o"
	@echo "... ProcessingTaskQueue.i"
	@echo "... ProcessingTaskQueue.s"
	@echo "... ProjectCreationContext.o"
	@echo "... ProjectCreationContext.i"
	@echo "... ProjectCreationContext.s"
	@echo "... ProjectFilesDialog.o"
	@echo "... ProjectFilesDialog.i"
	@echo "... ProjectFilesDialog.s"
	@echo "... ProjectOpeningContext.o"
	@echo "... ProjectOpeningContext.i"
	@echo "... ProjectOpeningContext.s"
	@echo "... ProjectPages.o"
	@echo "... ProjectPages.i"
	@echo "... ProjectPages.s"
	@echo "... ProjectReader.o"
	@echo "... ProjectReader.i"
	@echo "... ProjectReader.s"
	@echo "... ProjectWriter.o"
	@echo "... ProjectWriter.i"
	@echo "... ProjectWriter.s"
	@echo "... RecentProjects.o"
	@echo "... RecentProjects.i"
	@echo "... RecentProjects.s"
	@echo "... RelinkablePath.o"
	@echo "... RelinkablePath.i"
	@echo "... RelinkablePath.s"
	@echo "... RelinkablePathVisualization.o"
	@echo "... RelinkablePathVisualization.i"
	@echo "... RelinkablePathVisualization.s"
	@echo "... RelinkingDialog.o"
	@echo "... RelinkingDialog.i"
	@echo "... RelinkingDialog.s"
	@echo "... RelinkingListView.o"
	@echo "... RelinkingListView.i"
	@echo "... RelinkingListView.s"
	@echo "... RelinkingModel.o"
	@echo "... RelinkingModel.i"
	@echo "... RelinkingModel.s"
	@echo "... RelinkingSortingModel.o"
	@echo "... RelinkingSortingModel.i"
	@echo "... RelinkingSortingModel.s"
	@echo "... SelectedPage.o"
	@echo "... SelectedPage.i"
	@echo "... SelectedPage.s"
	@echo "... SettingsDialog.o"
	@echo "... SettingsDialog.i"
	@echo "... SettingsDialog.s"
	@echo "... SkinnedButton.o"
	@echo "... SkinnedButton.i"
	@echo "... SkinnedButton.s"
	@echo "... SmartFilenameOrdering.o"
	@echo "... SmartFilenameOrdering.i"
	@echo "... SmartFilenameOrdering.s"
	@echo "... StageListView.o"
	@echo "... StageListView.i"
	@echo "... StageListView.s"
	@echo "... StageSequence.o"
	@echo "... StageSequence.i"
	@echo "... StageSequence.s"
	@echo "... SystemLoadWidget.o"
	@echo "... SystemLoadWidget.i"
	@echo "... SystemLoadWidget.s"
	@echo "... TabbedDebugImages.o"
	@echo "... TabbedDebugImages.i"
	@echo "... TabbedDebugImages.s"
	@echo "... ThreadPriority.o"
	@echo "... ThreadPriority.i"
	@echo "... ThreadPriority.s"
	@echo "... ThumbnailBase.o"
	@echo "... ThumbnailBase.i"
	@echo "... ThumbnailBase.s"
	@echo "... ThumbnailFactory.o"
	@echo "... ThumbnailFactory.i"
	@echo "... ThumbnailFactory.s"
	@echo "... ThumbnailPixmapCache.o"
	@echo "... ThumbnailPixmapCache.i"
	@echo "... ThumbnailPixmapCache.s"
	@echo "... ThumbnailSequence.o"
	@echo "... ThumbnailSequence.i"
	@echo "... ThumbnailSequence.s"
	@echo "... TiffMetadataLoader.o"
	@echo "... TiffMetadataLoader.i"
	@echo "... TiffMetadataLoader.s"
	@echo "... TiffReader.o"
	@echo "... TiffReader.i"
	@echo "... TiffReader.s"
	@echo "... TiffWriter.o"
	@echo "... TiffWriter.i"
	@echo "... TiffWriter.s"
	@echo "... Utils.o"
	@echo "... Utils.i"
	@echo "... Utils.s"
	@echo "... WorkerThread.o"
	@echo "... WorkerThread.i"
	@echo "... WorkerThread.s"
	@echo "... XmlMarshaller.o"
	@echo "... XmlMarshaller.i"
	@echo "... XmlMarshaller.s"
	@echo "... XmlUnmarshaller.o"
	@echo "... XmlUnmarshaller.i"
	@echo "... XmlUnmarshaller.s"
	@echo "... main-cli.o"
	@echo "... main-cli.i"
	@echo "... main-cli.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... qrc_resources.o"
	@echo "... qrc_resources.i"
	@echo "... qrc_resources.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

